### ISSUE TITLE
save not opening with exepction error

### ISSUE THREAD

**Issue by EidosRunner** [Nxer/Twist-Space-Technology-Mod#1295]
### Describe the bug

i downloaded the pack from scratch added the TST and every time i try to create a solo world the internal server crash 

### How to reproduce the bug

i guess downloading the pack on a new instance and adding the mods 

### Which mod/modpack versions are you using?

GTNH : 2.9.0 beta 2 
tried with TST 0.8.0-beta1.1 and 0.8.0-beta1.0
BartWorks

### Crash log

NoSuchMethodError: bartworks.common.loaders.BioItemList.getPetriDish(Lbartworks/util/BioCulture;)Lnet/minecraft/item/ItemStack;

**Comment by Nxer** [comment]
will be fixed in new version when NH stable

**Comment by valdemartingkaer-gif** [comment]
it works on GT:NH 2.9.0 beta-1

**Comment by NightVision8210** [comment]
experiencing the same thing on 2.9.0 beta 3 btw
